version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/image_A-backend
hooks:
  AfterInstall:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
