version: 0.2

phases:
  install:
    commands:
      - cd Image_A-frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: Image_A-frontend/dist
